Correctly read tree using provided context
Without the change in the SpanSerialization.SpanDeserializer
newly added TestSpanSerialization.testNestedSerialization
would fail with:

```
java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class io.airlift.tracing.TestSpanSerialization$NestedSpan]

	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:151)
	at io.airlift.tracing.TestSpanSerialization.testNestedSerialization(TestSpanSerialization.java:75)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Trailing token (of type FIELD_NAME) found after value (bound as `java.util.Map`): not allowed as per `DeserializationFeature.FAIL_ON_TRAILING_TOKENS`
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 6, column: 3] (through reference chain: io.airlift.tracing.TestSpanSerialization$NestedSpan["inner"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:76)
	at com.fasterxml.jackson.databind.DeserializationContext.reportTrailingTokens(DeserializationContext.java:1887)
	at com.fasterxml.jackson.databind.ObjectMapper._verifyNoTrailingTokens(ObjectMapper.java:5160)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:5030)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3129)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2523)
	at io.airlift.tracing.SpanSerialization$SpanDeserializer.deserialize(SpanSerialization.java:72)
	at io.airlift.tracing.SpanSerialization$SpanDeserializer.deserialize(SpanSerialization.java:53)
```

when FAIL_ON_TRAILING_TOKENS is enabled.